name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a Node.js version compatible with your project

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build
        env:
          # Pass the VITE_BACKEND_URL during the build process
          VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }} # Assuming you have this as a GitHub Secret

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' # The secret you created
          projectId: 'collab-whiteboard-e68ad' # Your Firebase Project ID
          channelId: live # Deploy to the live channel
          
